# Generated by Django 4.2.7 on 2025-10-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_cars', models.PositiveIntegerField(default=0)),
                ('available_cars', models.PositiveIntegerField(default=0)),
                ('sold_cars', models.PositiveIntegerField(default=0)),
                ('featured_cars', models.PositiveIntegerField(default=0)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('contacted_leads', models.PositiveIntegerField(default=0)),
                ('pending_leads', models.PositiveIntegerField(default=0)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('confirmed_bookings', models.PositiveIntegerField(default=0)),
                ('pending_bookings', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('inquiry_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PopularCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('total_inquiries', models.PositiveIntegerField(default=0)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('views_today', models.PositiveIntegerField(default=0)),
                ('views_this_week', models.PositiveIntegerField(default=0)),
                ('views_this_month', models.PositiveIntegerField(default=0)),
                ('engagement_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='cars.car')),
            ],
            options={
                'ordering': ['-engagement_score', '-total_views'],
            },
        ),
        migrations.CreateModel(
            name='CarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='cars.car')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['car', 'viewed_at'], name='analytics_c_car_id_52b431_idx'), models.Index(fields=['ip_address', 'viewed_at'], name='analytics_c_ip_addr_ba4e1d_idx'), models.Index(fields=['session_key'], name='analytics_c_session_355da7_idx')],
            },
        ),
    ]
