# Generated by Django 4.2.7 on 2025-10-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
