# Generated by Django 4.2.7 on 2025-10-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter')], max_length=20, unique=True)),
                ('api_token', models.TextField(help_text='API access token for this platform')),
                ('page_id', models.CharField(blank=True, help_text='Page/Account ID for posting', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('auto_post_new_cars', models.BooleanField(default=True, help_text='Automatically post new cars')),
                ('post_template', models.TextField(blank=True, help_text='Template for posts. Use {car}, {price}, {year}, {make}, {model} placeholders')),
            ],
            options={
                'verbose_name': 'Social Media Account',
                'verbose_name_plural': 'Social Media Accounts',
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('post_id', models.CharField(blank=True, help_text='ID from social platform', max_length=200)),
                ('post_url', models.URLField(blank=True, help_text='Direct link to the post')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Schedule post for later', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.socialaccount')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='cars.car')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('car', 'account')},
            },
        ),
    ]
